### PR TITLE
updated release

### PR DESCRIPTION
**Pull request by fgimenez**

### CODE REVIEW

**Comment by elopio** [comment]
Why not updating the job names?

Anyway, we can do that later. +1.

**Comment by fgimenez** [comment]
Well, if we keep adding series for each release we will end up with a lot of jobs, maybe we could remove the old ones? Maybe the rolling name is a bit misleading, but we could have a set of jobs for the current release, what do you think?

**Comment by elopio** [comment]
I think we will open a rolling series in a couple of months, because we need to test the new things that are getting in yakety. So we will have 15.04, 16, and at some point rolling again.

**Comment by fgimenez** [comment]
ok, changed all the rolling names to 16

**Pull request merged**
