### PR TITLE
Use the docker images from the ubuntucore hub.

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
The images are building, I think. And you should have admin access to them, I think.

**Comment by fgimenez** [comment]
> The images are building, I think. And you should have admin access to them, I think.

Yes, thanks :) I've also transfered the base image for the slaves, jenkins-swarm-slave-ubuntu, they are building too.

Now we need to modify the Dockerfiles under `/containers` in this PR, changing the `FROM` field of jenkins-master and the two jenkins-slaves to point to this ubuntucore images (fgimenez -> ubuntucore)

**Comment by elopio** [comment]
DONE for jenkins-swarm-slave-ubuntu. I don't see the base image for master in the org repository.

**Comment by fgimenez** [comment]
Ok, the automated build wasn't created, it's now [1]. We need to change the source at [2] to use of it

[1] https://hub.docker.com/r/ubuntucore/jenkins-ubuntu/builds/
[2] https://github.com/ubuntu-core/snappy-jenkins/blob/master/containers/jenkins-master/Dockerfile

**Comment by elopio** [comment]
DONE DONE

**Comment by fgimenez** [comment]
Great, thanks!

**Pull request merged**
